force-app/core/objects/DiaperChange__c/DiaperChange__c.object-meta.xml
<CustomObject>
    <label>Diaper Change</label>
    <nameField>
        <displayFormat>DC-{0000}</displayFormat>
        <label>Diaper Change</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Diaper Changes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/core/objects/DiaperChange__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Wet</fullName>
                <default>true</default>
                <label>Wet</label>
            </value>
            <value>
                <fullName>Dirty</fullName>
            </value>
            <value>
                <fullName>Wet &amp; Dirty</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/core/objects/Feeding__c/Feeding__c.object-meta.xml
<CustomObject>
    <label>Feeding</label>
    <nameField>
        <displayFormat>F-{0000}</displayFormat>
        <label>Feeding</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Feedings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/core/objects/Feeding__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Bottle</fullName>
            </value>
            <value>
                <fullName>Left</fullName>
            </value>
            <value>
                <fullName>Right</fullName>
            </value>
            <value>
                <fullName>Left then Right</fullName>
            </value>
            <value>
                <fullName>Right then Left</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/core/objects/Weighing__c/Weighing__c.object-meta.xml
<CustomObject>
    <label>Weighing</label>
    <nameField>
        <displayFormat>W-{0000}</displayFormat>
        <label>Weighing</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Weighings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/core/objects/Weighing__c/fields/Feeding__c.field-meta.xml
<CustomField>
    <fullName>Feeding__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Feeding</label>
    <referenceTo>Feeding__c</referenceTo>
    <relationshipLabel>Related Weighings</relationshipLabel>
    <relationshipName>Weighings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/core/objects/Weighing__c/fields/Occurred__c.field-meta.xml
<CustomField>
    <fullName>Occurred__c</fullName>
    <defaultValue>NOW()</defaultValue>
    <label>Occurred</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

force-app/core/classes/TimelineEvent.cls
public with sharing class TimelineEvent implements Comparable {
    @AuraEnabled
    public DateTime eventDate;
    @AuraEnabled
    public String title;
    @AuraEnabled
    public String type;

    public TimelineEvent(SObject so) {
        switch on so {
            when DiaperChange__c dc {
                this.eventDate = dc.Occurred__c;
                this.title = dc.Type__c + ' Diaper Change';
                this.type = dc.Type__c.contains('Dirty')
                    ? 'diaper_dirty'
                    : 'diaper_wet';
            }
            when Feeding__c f {
                this.eventDate = f.Occurred__c;
                this.title = 'Feeding (' + f.Type__c + ')';
                this.type = 'feeding';
            }
            when Weighing__c w {
                this.eventDate = w.Occurred__c;
                this.title = 'Weighing';
                this.type = 'weighing';
            }
            when null {
                // Do Nothing
            }
            when else {
                this.eventDate = (DateTime)so.get('CreatedDate');
                this.title = (String)so.get('Name');
            }
        }
    }

    public Integer compareTo(Object compareTo) {
        TimelineEvent compareToEvent = (TimelineEvent)compareTo;

        Integer returnValue = 0;
        if (eventDate != compareToEvent.eventDate) {
            returnValue = eventDate < compareToEvent.eventDate
                ? 1
                : -1;
        }
        return returnValue;
    }
}