force-app/core/objects/DiaperChange__c/DiaperChange__c.object-meta.xml
<CustomObject>
    <label>Diaper Change</label>
    <nameField>
        <displayFormat>DC-{0000}</displayFormat>
        <label>Diaper Change</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Diaper Changes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/core/objects/Feeding__c/Feeding__c.object-meta.xml
<CustomObject>
    <label>Feeding</label>
    <nameField>
        <displayFormat>F-{0000}</displayFormat>
        <label>Feeding</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Feedings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/core/objects/Weighing__c/Weighing__c.object-meta.xml
<CustomObject>
    <label>Weighing</label>
    <nameField>
        <displayFormat>W-{0000}</displayFormat>
        <label>Weighing</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Weighings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/core/objects/Weighing__c/fields/Feeding__c.field-meta.xml
<CustomField>
    <fullName>Feeding__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Feeding</label>
    <referenceTo>Feeding__c</referenceTo>
    <relationshipLabel>Related Weighings</relationshipLabel>
    <relationshipName>Weighings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/core/classes/PadawanTimelineController.cls
public with sharing class PadawanTimelineController {

    @AuraEnabled(cacheable=true)
    public static List<TimelineEvent> fetchTimelineEvents(Id babyId) {
        List<TimelineEvent> events = new List<TimelineEvent>();
        Map<Id,DiaperChange__c> diaperChangesById = DiaperChangeSelector.getDiaperChangesByIdForBaby(babyId);
        if (!diaperChangesById.isEmpty()) {
            for (DiaperChange__c dc : diaperChangesById.values()) {
                events.add(
                    new TimelineEvent(dc)
                );
            }
        }
        Map<Id,Feeding__c> feedingsById = FeedingSelector.getFeedingsByIdForBaby(babyId);
        if (!feedingsById.isEmpty()) {
            for (Feeding__c f : feedingsById.values()) {
                events.add(
                    new TimelineEvent(f)
                );
            }
        }
        Map<Id,Weighing__c> weighingsById = WeighingSelector.getWeighingsByIdForBaby(babyId);
        if (!weighingsById.isEmpty()) {
            for (Weighing__c w : weighingsById.values()) {
                events.add(
                    new TimelineEvent(w)
                );
            }
        }
        events.sort();
        return events;
    }
}