force-app/core/objects/Feeding__c/Feeding__c.object-meta.xml
<CustomObject>
    <label>Feeding</label>
    <nameField>
        <displayFormat>F-{0000}</displayFormat>
        <label>Feeding</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Feedings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/core/objects/Feeding__c/fields/Baby__c.field-meta.xml
<CustomField>
    <fullName>Baby__c</fullName>
    <label>Baby</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Feedings</relationshipLabel>
    <relationshipName>Feedings</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/core/objects/Feeding__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Bottle</fullName>
            </value>
            <value>
                <fullName>Left</fullName>
            </value>
            <value>
                <fullName>Right</fullName>
            </value>
            <value>
                <fullName>Left then Right</fullName>
            </value>
            <value>
                <fullName>Right then Left</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/core/objects/Weighing__c/Weighing__c.object-meta.xml
<CustomObject>
    <label>Weighing</label>
    <nameField>
        <displayFormat>W-{0000}</displayFormat>
        <label>Weighing</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Weighings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/core/objects/Weighing__c/fields/Baby__c.field-meta.xml
<CustomField>
    <fullName>Baby__c</fullName>
    <label>Baby</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Weighings</relationshipLabel>
    <relationshipName>Weighings</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/core/objects/Weighing__c/fields/Feeding__c.field-meta.xml
<CustomField>
    <fullName>Feeding__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Feeding</label>
    <referenceTo>Feeding__c</referenceTo>
    <relationshipLabel>Related Weighings</relationshipLabel>
    <relationshipName>Weighings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/core/objects/Weighing__c/fields/InitialWeight__c.field-meta.xml
<CustomField>
    <fullName>InitialWeight__c</fullName>
    <inlineHelpText>Initial Weight in Grams</inlineHelpText>
    <label>Initial Weight</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/core/objects/Weighing__c/fields/Occurred__c.field-meta.xml
<CustomField>
    <fullName>Occurred__c</fullName>
    <defaultValue>NOW()</defaultValue>
    <label>Occurred</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

force-app/core/objects/Weighing__c/fields/PercentWeightGainFromFeeding__c.field-meta.xml
<CustomField>
    <fullName>PercentWeightGainFromFeeding__c</fullName>
    <formula>IF(
AND(
NOT(ISBLANK(InitialWeight__c)),
NOT(ISBLANK(PostFeedingWeight__c)),
InitialWeight__c &gt; 0),
WeightGainFromFeeding__c/InitialWeight__c,
0)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>% Weight Gain From Feeding</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/core/objects/Weighing__c/fields/PercentWeightGainSinceBirth__c.field-meta.xml
<CustomField>
    <fullName>PercentWeightGainSinceBirth__c</fullName>
    <formula>IF(
AND(
NOT(ISBLANK(Baby__r.BirthWeight__c)),
WeightGainSinceBirth__c &gt; 0),
WeightGainSinceBirth__c/Baby__r.BirthWeight__c,
0)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>% Weight Gain Since Birth</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/core/objects/Weighing__c/fields/PostFeedingWeight__c.field-meta.xml
<CustomField>
    <fullName>PostFeedingWeight__c</fullName>
    <inlineHelpText>Post-Feeding Weight in Grams</inlineHelpText>
    <label>Post-Feeding Weight</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/core/objects/Weighing__c/fields/WeightGainFromFeeding__c.field-meta.xml
<CustomField>
    <fullName>WeightGainFromFeeding__c</fullName>
    <formula>IF(
AND(
NOT(ISBLANK(InitialWeight__c)),
NOT(ISBLANK(PostFeedingWeight__c))),
PostFeedingWeight__c-InitialWeight__c,
0)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Weight Gain From Feeding</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/core/objects/Weighing__c/fields/WeightGainSinceBirth__c.field-meta.xml
<CustomField>
    <fullName>WeightGainSinceBirth__c</fullName>
    <formula>IF(
AND(
NOT(ISBLANK(Baby__r.BirthWeight__c)),
NOT(ISBLANK(PostFeedingWeight__c))),
PostFeedingWeight__c - Baby__r.BirthWeight__c,
IF(
AND(
NOT(ISBLANK(Baby__r.BirthWeight__c)),
NOT(ISBLANK(InitialWeight__c))),
InitialWeight__c - Baby__r.BirthWeight__c,
0))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Weight Gain Since Birth</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/core/classes/WeighingSelector.cls
public with sharing class WeighingSelector {

    public static Map<Id,Weighing__c> getWeighingsByIdForBaby(Id babyId) {
        return new Map<Id,Weighing__c>([
            SELECT
            Id,
            Name,
            Baby__c,
            Feeding__c,
            Feeding__r.Name,
            Feeding__r.Type__c,
            Occurred__c,
            InitialWeight__c,
            PercentWeightGainFromFeeding__c,
            PercentWeightGainSinceBirth__c,
            PostFeedingWeight__c,
            WeightGainFromFeeding__c,
            WeightGainSinceBirth__c
            FROM Weighing__c
            WHERE Baby__c = :babyId
        ]);
    }
}